name: Automatically merge eligible pull requests
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status:
jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - name: Merge pull requests labeled "automerge"
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_PAT }}  # trigger other workflows
